export const FETCHED_DATA_SUCCESS = 'FETCHED_DATA_SUCCESS';
export const EMPLOYEES_DATA_LOADING = 'EMPLOYEES_DATA_LOADING';
export const EMPLOYEES_HAVE_ERRORED = 'EMPLOYEES_DATA_HAVE_ERRORED';
export const ADD_BIRTHDAY = 'ADD_BIRTHDAY';
export const DELETE_BIRTHDAY = 'DELETE_BIRTHDAY';